openapi: 3.0.0

info:
  title: webflux api
  version: 1.0.0

servers:
  - url: http://localhost:8081
    description: Local Server

paths:
  /webflux/one:
    post:
      summary: webflux services one
      operationId: webFluxService
      tags:
        - webflux
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Webflux'
      responses:
        '200':
          description: web flux info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Webflux'

components:
  schemas:
    Webflux:
      type: object
      properties:
        id:
          type: number
        name:
          type: string

